src/Form/BlockTemplateType.php
<?php

namespace AutoJM\CmsBundle\Form;

use AutoJM\CmsBundle\Services\TemplateProvider;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class TemplateType
 *
 * Type of template defined in ajm_cms.yaml
 */
class BlockTemplateType extends AbstractType
{
    private $provider;

    public function __construct(TemplateProvider $provider)
    {
        $this->provider = $provider;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            [
                'choices' => $this->provider->getTemplateList(),

            ]
        );
    }

    public function getParent()
    {
        return ChoiceType::class;
    }
}

src/Form/CmsContentsType.php
<?php

namespace AutoJM\CmsBundle\Form;

use Sonata\Form\EventListener\ResizeFormListener;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CmsContentsType extends SonataCollectionType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder->addEventSubscriber(new ResizeFormListener(
            $options['type'],
            $options['type_options'],
            $options['modifiable'],
            $options['pre_bind_data_callback']
        ));
    }

    public function buildView(FormView $view, FormInterface $form, array $options): void
    {
        $view->vars['btn_add'] = $options['btn_add'];
        $view->vars['btn_catalogue'] = $options['btn_catalogue'];
        $view->vars['role_admin'] = $options['role_admin'];
    }


    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'modifiable'             => false,
            'type'                   => TextType::class,
            'type_options'           => [],
            'pre_bind_data_callback' => null,
            'btn_add'                => 'link_add',
            'btn_catalogue'          => 'SonataFormBundle',
            'role_admin'             => false,
        ]);
    }


    public function getBlockPrefix(): string
    {
        return 'cms_contents';
    }

}

src/Form/CmsRouteParamsType.php
<?php

namespace AutoJM\CmsBundle\Form;

use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\CallbackTransformer;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Regex;
use AutoJM\CmsBundle\Entity\CmsRoute;
use Symfony\Contracts\Translation\TranslatableInterface;

class CmsRouteParamsType extends AbstractType
{
    /**
     * @var EntityManagerInterface
     */
    protected $em;
    private $cmsConfig;

    /**
     * @inheritDoc
     */
    public function __construct(EntityManagerInterface $em, $cmsConfig)
    {
        $this->em        = $em;
        $this->cmsConfig = $cmsConfig;
    }

    /**
     * @inheritDoc
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $config = $options['config'];
        /** @var CmsRoute $route */
        $route  = $options['route'];
        $object = $options['object'];
        $locale = $object->getPage()->getSite()->getLocale();

        $defaults     = json_decode($route->getDefaults(), true);
        $requirements = json_decode($route->getRequirements(), true);
        $entities     = array_merge($config['params'], $route->normalizeEntities());

        foreach ($route->getParams() as $name) {
            $param = $entities[$name] ?? null;
            $type  = !empty($param['entity']) ? EntityType::class : TextType::class;
            $opts  = !empty($param['entity']) ? [
                'class'        => $param['entity'],
                'choice_value' => function ($entity = null) use ($param, $locale) {
                    $getter = 'get' . ucfirst($param['property']);
                    if ($this->cmsConfig['multilingual'] === true && is_subclass_of($entity, TranslatableInterface::class)) {
                        return $entity ? $entity->trans($locale)->$getter() : '';
                    }

                    return $entity ? $entity->$getter() : '';
                },
                'required'     => false,
            ] : [
                'required' => false,
            ];

            if (isset($defaults[$name])) {
                if (empty($param['entity'])) {
                    $opts['attr']['placeholder'] = $defaults[$name];
                } else {
                    $opts['choice_attr'] = function ($choice, $key, $value) use ($defaults, $name) {
                        $attr = [];
                        if ($value == $defaults[$name]) {
                            $attr['selected'] = 'selected';
                        }

                        return $attr;
                    };
                }
            }
            if (isset($requirements[$name]) && !empty($requirements[$name]) && $type !== EntityType::class && !isset($defaults[$name])) {
                $opts['constraints'][] = new Regex([
                    'pattern' => '/' . $requirements[$name] . '/',
                    'match'   => true,
                ]);

                if (!preg_match('/' . $requirements[$name] . '/', '')) {
                    $opts['constraints'][] = new NotBlank();
                }
            }

            $builder->add($name, $type, $opts);
        }

        $builder->addModelTransformer(new CallbackTransformer(
            function ($values) use ($entities, $object) {
                if ($values != null) {
                    $values = json_decode($values, true);
                    foreach ($values as $name => $value) {
                        $param = $entities[$name] ?? null;
                        if ($param && isset($param['entity']) && isset($param['property'])) {
                            if ($this->cmsConfig['multilingual'] == true && is_subclass_of($param['entity'], TranslatableInterface::class)) {
                                $method = 'findOneBy' . ucfirst($param['property']);
                                $locale = $object->getPage()->getSite()->getLocale();
                                $entity = $this->em->getRepository($param['entity'])->$method($value, $locale);
                            } else {
                                $entity = $this->em->getRepository($param['entity'])->findOneBy([$param['property'] => $value]);
                            }
                            $values[$name] = $entity ?? null;
                        }
                    }
                }

                return $values;
            },
            function ($values) use ($entities, $locale) {
                foreach ($values as $name => $value) {
                    $param = $entities[$name] ?? null;
                    if ($param && isset($param['property'])) {
                        $getter = 'get' . ucfirst($param['property']);
                        if (method_exists($value, $getter)) {
                            if ($this->cmsConfig['multilingual'] == true && is_subclass_of($value, TranslatableInterface::class)) {
                                $values[$name] = $value->translate($locale)->$getter();
                            } else {
                                $values[$name] = $value->$getter();
                            }
                        }
                    }
                }

                return json_encode($values, JSON_THROW_ON_ERROR);
            }
        ));
    }

    /**
     * @inheritDoc
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setRequired('config');
        $resolver->setRequired('route');
        $resolver->setRequired('object');
    }

    /**
     * @inheritDoc
     */
    public function getBlockPrefix()
    {
        return 'cms_route_params';
    }
}

src/Form/CustomContents/SortableEntityType.php
<?php

namespace AutoJM\CmsBundle\Form\CustomContents;

use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use AutoJM\CmsBundle\Entity\CmsContent;
use AutoJM\CmsBundle\Models\CustomContents\SortableEntity;
use AutoJM\CmsBundle\Services\CmsSonataFormBuilderHelper;

class SortableEntityType extends AbstractType
{
    /**
     * @var CmsSonataFormBuilderHelper
     */
    private CmsSonataFormBuilderHelper $helper;

    /**
     * EquipmentType constructor.
     * @param CmsSonataFormBuilderHelper $helper
     */
    public function __construct(CmsSonataFormBuilderHelper $helper)
    {
        $this->helper = $helper;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('position', HiddenType::class);
        if ($options['useModelListType']) {
            $this->helper->buildModelListType($builder, 'entity', CmsContent::class,
                $options['entity_class'], [
                    'label'           => false,
                    'link_parameters' => $options['link_parameters']
                ]);
        } else {
            $builder->add('entity', EntityType::class, [
                'class' => $options['entity_type']
            ]);
        }

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setRequired('entity_class');

        $resolver->setDefaults([
            'data_class'       => SortableEntity::class,
            'useModelListType' => false,
            'link_parameters'  => [],
            'csrf_protection'  => false
        ]);
    }
}

src/Form/CustomContents/Transformer/SortableCollectionTransformer.php
<?php


namespace AutoJM\CmsBundle\Form\CustomContents\Transformer;

use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Form\DataTransformerInterface;
use Symfony\Component\Form\Exception\TransformationFailedException;
use AutoJM\CmsBundle\Models\CustomContents\SortableEntity;

class SortableCollectionTransformer implements DataTransformerInterface
{
    /**
     * @var EntityManagerInterface
     */
    private $em;
    private $entity;

    public function __construct(EntityManagerInterface $em, $entity)
    {
        $this->em     = $em;
        $this->entity = $entity;
    }

    /**
     *
     * @param mixed $value The value in the original representation
     *
     * @return mixed The value in the transformed representation
     *
     * @throws TransformationFailedException when the transformation fails
     */
    public function transform($value)
    {
        $rp = $this->em->getRepository($this->entity);

        $collection = [];
        if (is_array($value)) {
            foreach ($value as $data) {
                $sortableEntity           = new SortableEntity();
                $sortableEntity->entity   = $rp->find((int)$data['entity']);
                $sortableEntity->position = $data['position'];

                $collection[] = $sortableEntity;
            }
        }

        return $collection;
    }

    /**
     * @param mixed $value The value in the transformed representation
     *
     * @return mixed The value in the original representation
     *
     * @throws TransformationFailedException when the transformation fails
     */
    public function reverseTransform($value)
    {
        $data = [];
        if (is_array($value)) {
            foreach ($value as $sortableEntity) {
                if (method_exists($sortableEntity->entity, 'getId')) {
                    $sortableEntity->entity = $sortableEntity->entity->getId();
                    if ($sortableEntity->entity){
                        $data[] = $sortableEntity;
                    }
                }
            }

            $data = array_values($data);
            usort($data, function (SortableEntity $a, SortableEntity $b) {
                return $a->position < $b->position ? -1 : 1;
            });

        }else{
            $data = $value;
        }

        return json_encode($data, true);
    }
}

src/Form/Filter/HiddenFilterType.php
<?php

namespace AutoJM\CmsBundle\Form\Filter;

use Sonata\DatagridBundle\Filter\FilterInterface;
use Sonata\DatagridBundle\ProxyQuery\ProxyQueryInterface;

class HiddenFilterType implements FilterInterface
{

    /**
     * @inheritDoc
     */
    public function filter(
        ProxyQueryInterface $queryBuilder,
        string              $alias,
        string              $field,
        string              $value
    ): void
    {
        // TODO: Implement filter() method.
    }

    /**
     * @inheritDoc
     */
    public function apply($query, $value): void
    {
        // TODO: Implement apply() method.
    }

    public function getName(): ?string
    {
        // TODO: Implement getName() method.
    }

    public function getFormName(): string
    {
        // TODO: Implement getFormName() method.
    }

    public function getLabel(): ?string
    {
        // TODO: Implement getLabel() method.
    }

    public function setLabel(string $label): void
    {
        // TODO: Implement setLabel() method.
    }

    public function getDefaultOptions(): array
    {
        // TODO: Implement getDefaultOptions() method.
    }

    /**
     * @inheritDoc
     */
    public function getOption(string $name, $default = null)
    {
        // TODO: Implement getOption() method.
    }

    /**
     * @inheritDoc
     */
    public function setOption(string $name, $value): void
    {
        // TODO: Implement setOption() method.
    }

    public function initialize(string $name, array $options = []): void
    {
        // TODO: Implement initialize() method.
    }

    public function getFieldName(): string
    {
        // TODO: Implement getFieldName() method.
    }

    public function getFieldOptions(): array
    {
        // TODO: Implement getFieldOptions() method.
    }

    public function getFieldType(): string
    {
        // TODO: Implement getFieldType() method.
    }

    /**
     * @inheritDoc
     */
    public function getRenderSettings(): array
    {
        // TODO: Implement getRenderSettings() method.
    }

    public function isActive(): bool
    {
        // TODO: Implement isActive() method.
    }

    /**
     * @inheritDoc
     */
    public function setCondition(string $condition): void
    {
        // TODO: Implement setCondition() method.
    }

    public function getCondition(): string
    {
        // TODO: Implement getCondition() method.
    }

    public function getTranslationDomain(): string
    {
        // TODO: Implement getTranslationDomain() method.
    }
}

src/Form/GlobalVarsType.php
<?php

namespace AutoJM\CmsBundle\Form;

use AutoJM\CmsBundle\Entity\CmsPage;
use AutoJM\CmsBundle\Services\CmsContentVars;
use AutoJM\CmsBundle\Services\TemplateProvider;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class TemplateType
 *
 * Type of template defined in ajm_cms.yaml
 */
class GlobalVarsType extends AbstractType
{
    protected $globalVars;
    protected $globalVarsDefinition;
    protected TemplateProvider $pageProvider;

    public function __construct(TemplateProvider $pageProvider, ContainerInterface $container, $globalVarsDefinition)
    {
        $this->pageProvider = $pageProvider;
        $this->globalVarsDefinition = $globalVarsDefinition;
        $this->globalVars   = $container->get($globalVarsDefinition['global_service']);
    }

    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        /** @var CmsPage $page */
        $page       = $options['page'];
        $config     = $this->pageProvider->getConfigurationFor($page->getTemplate());
        $vars       = !empty($config['entityVars']) ? $config['entityVars']::getAvailableVars() : [];

        $route = $page->getRoute();
        $routeEntities = $route->getListEntities();
        $entitiesVars = $this->globalVarsDefinition['entities'] ?? [];
        foreach ($route->getAttributes() as $param) {
            if (isset($routeEntities[$param])) {
                $entity = $routeEntities[$param];
                $entityVar = $entitiesVars[$entity] ?? null;
                if ($entityVar) {
                    $vars = array_merge($entityVar::getAvailableVars(), $vars);
                }
            } else {
                $vars = array_merge([$param], $vars);
            }
        }
        $vars = array_merge($this->globalVars::getAvailableVars(), $vars);

        $d          = CmsContentVars::getDelimiters();
        $vars = array_map(static function ($value) use ($d) {
            return $d['s'] . $value . $d['e'];
        }, $vars);

        $view->vars['user_vars'] = $vars;

        parent::buildView($view, $form, $options);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'page' => null,
        ]);
    }

    public function getBlockPrefix()
    {
        return 'cms_global_vars';
    }

    public function getParent()
    {
        return TextType::class;
    }
}

src/Resources/views/form/auto_trans_form_label.html.twig
{% extends "form_div_layout.html.twig" %}

{% block form_label %}
    {% spaceless %}
        {% import _self as macros %}

        {% if label is empty and label is not same as(false) %}
            {% set label = macros.form_parent_name(form)|trim %}
        {% endif %}

        {{ parent() }}

    {% endspaceless %}
{% endblock form_label %}

{% macro form_parent_name(form, prefix) %}
    {% spaceless %}

        {% import _self as macros %}

        {% set prefix = prefix|default(false) %}

        {% if form.parent is empty %}
            {{ form.vars.name }}.labels
        {% else %}
            {% if form.vars.compound and not prefix %}
                {{ macros.form_parent_name(form.parent) }}.{{ form.vars.name }}.label
            {% else %}
                {{ macros.form_parent_name(form.parent, true) }}.{{ form.vars.name }}
            {% endif %}
        {% endif %}

    {% endspaceless %}
{% endmacro %}

src/Resources/views/form/auto_trans_form_label_bootstrap_4.html.twig
{% extends "bootstrap_4_layout.html.twig" %}

{% block form_label %}
    {% spaceless %}
        {% import _self as macros %}

        {% if label is empty and label is not same as(false) %}
            {% set label = macros.form_parent_name(form)|trim %}
        {% endif %}

        {{ parent() }}

    {% endspaceless %}
{% endblock form_label %}

{% block checkbox_radio_label %}
    {% spaceless %}
        {% import _self as macros %}

        {% if label is empty and label is not same as(false) %}
            {% set label = macros.form_parent_name(form)|trim %}
        {% endif %}

        {{ parent() }}

    {% endspaceless %}
{% endblock checkbox_radio_label %}

{% macro form_parent_name(form, prefix) %}
    {% spaceless %}

        {% import _self as macros %}

        {% set prefix = prefix|default(false) %}

        {% if form.parent is empty %}
            {{ form.vars.name }}.labels
        {% else %}
            {% if form.vars.compound and not prefix %}
                {{ macros.form_parent_name(form.parent) }}.{{ form.vars.name }}.label
            {% else %}
                {{ macros.form_parent_name(form.parent, true) }}.{{ form.vars.name }}
            {% endif %}
        {% endif %}

    {% endspaceless %}
{% endmacro %}

src/Resources/views/form/cms_contents_type.html.twig
{% block cms_contents_widget %}
    <div class="panel-group" id="contents_collapse" role="tablist" aria-multiselectable="true">
        {% for item in form.children %}
            <div class="panel">
                <div class="panel-heading" role="tab" id="heading_{{ loop.index }}">
                    <div class="align-left">
                        <h4 class="panel-title">
                            <a role="button" data-toggle="collapse" href="#collapse_{{ loop.index }}"
                               aria-expanded="true" aria-controls="collapse_{{ loop.index }}">
                                {{ item.label.vars.value }}
                            </a>
                            {% if item.vars.value.help is not empty %}
                                <i class="fa fa-info-circle" data-toggle="tooltip" data-placement="top"
                                   title="{{ item.vars.value.help }}"></i>
                            {% endif %}
                        </h4>
                    </div>
                    <div class="align-right">
                        {% if role_admin %}
                            <div class="info">
                                {% if item.type is defined %}
                                    {{ choice_label(item.type.vars.choices, item.type.vars.value) }}
                                {% endif %}
                                {% if item.code is defined %}
                                    <code>{{ item.code.vars.value }}</code>
                                {% endif %}
                            </div>
                        {% endif %}
                        <div class="enable">
                            {{ form_widget(item.active) }}
                        </div>
                        <div class="btn_arrow">
                            <button type="button" class="class btn btn-default btn-sm collapsed" data-toggle="collapse"
                                    data-target="#collapse_{{ loop.index }}" aria-expanded="true"
                                    aria-controls="collapse_{{ loop.index }}">
                                <i class="glyphicon glyphicon-menu-up"></i>
                            </button>
                        </div>
                    </div>
                </div>
                <div id="collapse_{{ loop.index }}"
                     class="panel-collapse collapse {% if item.vars.value.collapseOpen %} in{% endif %}" role="tabpanel"
                     aria-labelledby="heading_{{ loop.index }}">
                    <div class="panel-body">
                        {% if item.parent_heritance is defined %}
                            <div class="inherit">
                                {{ form_widget(item.parent_heritance) }}
                            </div>
                        {% endif %}

                        {% if item.value is defined %}
                            {{ form_widget(item.value) }}
                        {% endif %}
                        {% if item.media is defined %}
                            {{ form_widget(item.media) }}
                        {% endif %}
                        {% if item.sharedBlockList is defined %}
                            {{ form_widget(item.sharedBlockList) }}
                        {% endif %}
                        <div style="display: none">
                            {{ form_widget(item.label) }}
                            {% if item.code is defined %}
                                {{ form_widget(item.code) }}
                            {% endif %}
                            {% if item.type is defined %}
                                {{ form_widget(item.type) }}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

src/Resources/views/form/cms_global_vars_type.html.twig
{% block cms_global_vars_widget %}
	{% for var in user_vars %}
		<code class="content-var">{{ var }}</code>
	{% endfor %}
{% endblock %}

src/Resources/views/form/cms_menu_icon_widget.html.twig
{% block cms_menu_icon_widget %}


    <div class="input-group">
        {{ form_widget(form) }}
        <span class="input-group-addon" id="{{ form.vars.id }}_book" style="cursor: pointer"><i class="fa fa-book"></i></span>
    </div>

    <div class="cms-menu-icon-set" id="{{ form.vars.id }}_library">
        <div class="form-inline">
            <input id="{{ form.vars.id }}_filter" type="text" class="form-control" placeholder="Filter" style="width: calc(100% - 35px)">
            <span class="btn btn-sm btn-danger" onclick="$('#{{ form.vars.id }}_library').removeClass('open');"><i class="fa fa-close"></i></span>
        </div>
        <div class="items" id="{{ form.vars.id }}_items">
            {% for icon, label in iconSet %}
                <button type="button" data-icon="{{ icon }}" data-label="{{ label }}"><i class="{{ icon }}"></i></button>
            {% endfor %}
        </div>
    </div>

    <script>

    $(document)
      .ready(function () {
        var $buttons = $('#{{ form.vars.id }}_items').find('button');

        $buttons.on('click', function () {
          $('#{{ form.vars.id }}').val($(this).data('icon'));
          $('#{{ form.vars.id }}_library').removeClass('open');
        })

        $('#{{ form.vars.id }}_filter')
          .on('keyup', function () {
            var val = $(this).val();

            $buttons.each(function( index ) {
              if ($(this).data('label').match(val)) {
                $(this).removeClass('hide');
              } else {
                $(this).addClass('hide');
              }
            });

          });

        $('#{{ form.vars.id }}_book')
          .on('click', function () {
              $('#{{ form.vars.id }}_library').addClass('open');
          });
      });


    </script>
{% endblock %}

src/Resources/views/form/cms_multilingual_type.html.twig
{% block cms_multilingual_page_widget %}
    {% set currentPage = sonata_admin.admin.subject %}
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="150px">Site</th>
            <th width="50px">Locale</th>
            <th>Page</th>
            <th width="100px">Action</th>
        </tr>
        </thead>
        <tbody>
        {% for site in sites %}
            <tr>
                <td>{{ site.label }}</td>
                <td>{{ site.locale }}</td>
                <td>{{ form_widget(form.children[site.id]) }}</td>
                <td>
                    {% if form.children[site.id].vars.value != null %}
                        <a href="{{ sonata_admin.admin.generateObjectUrl('edit', form.children[site.id].vars.data) }}" class="btn btn-primary" style="width: 100%"><i class="fa fa-pencil"></i>&nbsp;Modifier</a>
                    {% else %}
                        <a href="{{ sonata_admin.admin.generateUrl('create', {id: site.id, refId: currentPage.id }) }}" class="btn btn-primary" style="width: 100%"><i class="fa fa-plus-square"></i>&nbsp;Créer</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

src/Resources/views/form/cms_nested_move_radio.html.twig
{%- block radio_widget -%}
    <div class="nested_move_item">
        <input type="radio" data-sonata-icheck="false" {{ block('widget_attributes') }}{% if value is defined %} value="{{ value }}"{% endif %}{% if checked %} checked="checked"{% endif %} />
        <label for="{{ id }}" data-label-text="{{ value |trans({}, 'ajm_cms') }}">
            <img class="move-mode-img" src="{{ asset('bundles/ajmcms/img/NesteMoveIcons/'~value~'.png') }}" alt="" style="cursor: pointer">
        </label>
    </div>
{%- endblock radio_widget -%}

src/Resources/views/form/cms_route_params.html.twig
{% block cms_route_params_widget %}
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="150px">Paramètre</th>
            <th>Valeur</th>
        </tr>
        </thead>
        <tbody>
        {% for item in form.children %}
            <tr>
                <td>{{ form_label(item) }}</td>
                <td>
                    <div class="form-group {% if item.vars.errors.count > 0 %}has-error{% endif %}">
                        <div class="sonata-ba-field sonata-ba-field-standard-natural {% if item.vars.errors.count > 0 %}sonata-ba-field-error{% endif %}">
                            {{ form_widget(item) }}
                            {% if item.vars.errors.count > 0 %}
                                <div class="help-block sonata-ba-field-error-messages">
                                    {{ form_errors(item) }}
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock cms_route_params_widget %}