src/Form/PageTemplateType.php
<?php

namespace AutoJM\CmsBundle\Form;

use AutoJM\CmsBundle\Services\TemplateProvider;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class TemplateType
 *
 * Type of template defined in ajm_cms.yaml
 */
class PageTemplateType extends AbstractType
{
    private $provider;

    public function __construct(TemplateProvider $provider)
    {
        $this->provider = $provider;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            [
                'choices' => $this->provider->getTemplateList(),
            ]
        );
    }

    public function getParent()
    {
        return ChoiceType::class;
    }

    /**
     * @return TemplateProvider
     */
    public function getProvider(): TemplateProvider
    {
        return $this->provider;
    }
}

src/Resources/views/menu/edit.html.twig
{% extends '@SonataAdmin/CRUD/base_edit.html.twig' %}

{% block sonata_form_actions %}
    {% if app.request.isxmlhttprequest %}
        {# NEXT_MAJOR: remove default filter #}
        {% if objectId|default(admin.id(object)) is not null %}
            <button type="submit" class="btn btn-success" name="btn_update_and_list"><i class="fa fa-save" aria-hidden="true"></i> {{ 'btn_update'|trans({}, 'SonataAdminBundle') }}</button>
            {% if admin.hasRoute('delete') and admin.hasAccess('delete', object) %}
                {{ 'delete_or'|trans({}, 'SonataAdminBundle') }}
                <a class="btn btn-danger" href="{{ admin.generateObjectUrl('delete', object) }}">
                    <i class="fa fa-minus-circle" aria-hidden="true"></i> {{ 'link_delete'|trans({}, 'SonataAdminBundle') }}
                </a>
            {% endif %}
        {% else %}
            <button type="submit" class="btn btn-success" name="btn_create_and_list"><i class="fa fa-plus-circle" aria-hidden="true"></i> {{ 'btn_create'|trans({}, 'SonataAdminBundle') }}</button>
        {% endif %}
    {% else %}
        {% if admin.supportsPreviewMode %}
            <button class="btn btn-info persist-preview" name="btn_preview" type="submit">
                <i class="fa fa-eye" aria-hidden="true"></i>
                {{ 'btn_preview'|trans({}, 'SonataAdminBundle') }}
            </button>
        {% endif %}
        {# NEXT_MAJOR: remove default filter #}
        {% if objectId|default(admin.id(object)) is not null %}
            <button type="submit" class="btn btn-success" name="btn_update_and_edit"><i class="fa fa-save" aria-hidden="true"></i> {{ 'btn_update_and_edit_again'|trans({}, 'SonataAdminBundle') }}</button>

            {% if admin.hasRoute('list') and admin.hasAccess('list') %}
                <button type="submit" class="btn btn-success" name="btn_update_and_list"><i class="fa fa-save"></i> <i class="fa fa-list" aria-hidden="true"></i> {{ 'btn_update_and_return_to_list'|trans({}, 'SonataAdminBundle') }}</button>
            {% endif %}

            {% if admin.hasRoute('delete') and admin.hasAccess('delete', object) %}
                {{ 'delete_or'|trans({}, 'SonataAdminBundle') }}
                <a class="btn btn-danger" href="{{ admin.generateObjectUrl('delete', object) }}"><i class="fa fa-minus-circle" aria-hidden="true"></i> {{ 'link_delete'|trans({}, 'SonataAdminBundle') }}</a>
            {% endif %}

            {% if admin.isAclEnabled() and admin.hasRoute('acl') and admin.hasAccess('acl', object) %}
                <a class="btn btn-info" href="{{ admin.generateObjectUrl('acl', object) }}"><i class="fa fa-users" aria-hidden="true"></i> {{ 'link_edit_acl'|trans({}, 'SonataAdminBundle') }}</a>
            {% endif %}
        {% else %}
            {% if admin.hasroute('edit') and admin.hasAccess('edit') %}
                <button class="btn btn-success" type="submit" name="btn_create_and_edit"><i class="fa fa-save" aria-hidden="true"></i> {{ 'btn_create_and_edit_again'|trans({}, 'SonataAdminBundle') }}</button>
            {% endif %}
            {% if admin.hasroute('list') and admin.hasAccess('list') %}
                <button type="submit" class="btn btn-success" name="btn_create_and_list"><i class="fa fa-save"></i> <i class="fa fa-list" aria-hidden="true"></i> {{ 'btn_create_and_return_to_list'|trans({}, 'SonataAdminBundle') }}</button>
            {% endif %}
            <button class="btn btn-success" type="submit" name="btn_create_and_create"><i class="fa fa-plus-circle" aria-hidden="true"></i> {{ 'btn_create_and_create_a_new_one'|trans({}, 'SonataAdminBundle') }}</button>
        {% endif %}
    {% endif %}
{% endblock %}

src/Resources/views/menu/knp_menu.html.twig
{% extends 'knp_menu.html.twig' %}

{%- block linkElement -%}{% import _self as knp_menu %}<a href="{{ item.uri }}"{{ knp_menu.attributes(item.linkAttributes) }}>{% if item.getExtra('icon_class') is not null %}<i class="{{ item.getExtra('icon_class') }}"></i>{% endif %}{{ block('label') }}</a>{%- endblock -%}

{%- block spanElement -%}{% import _self as knp_menu %}<span{{ knp_menu.attributes(item.labelAttributes) }}>{% if item.getExtra('icon_class') is not null %}<i class="{{ item.getExtra('icon_class') }}"></i>{% endif %}{{ block('label') }}</span>{%- endblock -%}

src/Resources/views/menu/list.html.twig
{% extends base_template %}

{%- block actions -%}
    {% if admin.datagrid.results > 0 %}
        <li>
            <a class="sonata-action-element sonata-action-element__cms-menu" href="{{ admin.generateUrl('create', {target: admin.datagrid.results[0].id}) }}">
                <i class="fa fa-plus-circle" aria-hidden="true"></i>
                {{ 'link_action_create'|trans({}, 'SonataAdminBundle') }}
            </a>
        </li>
    {% endif %}
{%- endblock -%}

{%- block tab_menu -%}
    {{ knp_menu_render(admin.sidemenu(action), {
        'currentClass': 'active',
        'template': get_global_template('tab_menu_template')
    }, 'twig') }}
{%- endblock -%}

{% block list_table %}
    {% set rootNodes = admin.datagrid.results %}
    <div class="col-xs-6 col-md-6">
        {% set label = false %}

        {% for rootNode in rootNodes %}
            {% set items = rootNode.children %}
            <div class="cmsMenuAdmin tab-pane" data-move-url="{{ url('admin_autojm_cms_cmsmenu_move', [], true) }}">
                {% for item in items if item.lvl == 1 and item.parent == rootNode %}
                    <div class="box box-primary">
                        <div class="box-header item-data" data-id="{{ item.id }}" data-edit-url="{{ admin.generateUrl('edit', {id: item.id}) }}" data-add-url="{{ admin.generateUrl('create', {target: item.id}) }}">
                            <h4 class="box-title">{{ item.name }} <code>{{ item.code }}</code></h4>
                            <button class="cms-menu-item__btn-edit"><i class="fa fa-pencil"></i></button>
                            <button class="cms-menu-item__btn-add"><i class="fa fa-plus"></i></button>
                        </div>
                        <div class="box-body">
                            {% set menu = knp_menu_get('cmsAdminMenu', [], {item: item, admin: admin}) %}
                            {{ knp_menu_render(menu, [], 'cms_menu_admin_renderer') }}
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
        <br><br>
    </div>
    <div class="col-xs-6 col-md-6">
        <div class="edit-container" style="display: none">

        </div>
    </div>
    <script>
      var time = 100;
      $(document).ready(function () {
        $('#add_global_btn').on('click', function (e) {
          var url = $(this).data('url');
          var id = $('.menu-tab.active').data('id');
          showForm(url + '?target=' + id)
        })

      })

      function showForm (url) {
        setTimeout(function () {

          $.get(url, function (response) {
            $('.edit-container').empty().append(response);
            $('.edit-container').fadeIn();
          })
        }, time)
      }
    </script>
{% endblock %}

src/Resources/views/menu/menu_admin_renderer.html.twig
{% extends 'knp_menu.html.twig' %}

{% block spanElement %}
    {% import 'knp_menu.html.twig' as knp_menu %}
    <div{{ knp_menu.attributes(item.labelAttributes) }}>
        <span>{% if item.name != 'ghost' %}<span class="glyphicon glyphicon-move" aria-hidden="true"></span>{% endif %} {{ block('label') }}</span>
        {% if item.name != 'ghost' %}
            <div class="cms-menu-item__btn">
                <button class="cms-menu-item__btn-edit"><i class="fa fa-pencil"></i></button>
                <button class="cms-menu-item__btn-add"><i class="fa fa-plus"></i></button>
                {#{% if item.children|length > 1 %}#}
                    {#<button class="cms-menu-item__btn-hide_child"><i class="fa fa-sort-up"></i></button>#}
                {#{% endif %}#}
            </div>
        {% endif %}
    </div>
{% endblock %}